name: Maven Test on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'  # Specify the desired Java distribution

    - name: Set Environment Variable
      run: |
         export LT_ACCESS_KEY=rakcBoBYHiy8BW7osVi4N1LGYjgJhRfAwvL1pPUvwCA1wfNChd
         export LT_USERNAME=mohammadk

    - name: Build and Test
      run: mvn test
